= familyBot - бот для модерации группы в Telegram

:sectnums:
:sectnumlevels: 5
:toc: left
:toclevels: 4
:toc-title: Оглавление

== Описание
`familyBot` это бот для группы в Telegram, который предназначен для поддержания доброжелательной атмосферы в семейном чате.

== Основные фичи и идеи
. Напоминание о днях рождения родственников;
. Напоминание о памятных датах и важных датах для семьи;
. Поздравление с различными праздниками;
. Интеграция с сервисом погоды;
. Интеграция с chatGPT.

=== Напоминание о днях рождения родственников
Для этого нам потребуется `интеграция с базой данных` или с коллекцией в файле.
На момент написания документации наиболее предпочтительным выглядит интеграция с `БД`, это мне позволит безгранично расширять коллекции данных под любые требования в будующем, а так же `SQL` то просто удобно.

В первой итерации коллекция предполагается минимальной: Фамилия, Имя и дата рождения.

=== Напоминание о памятных датах и важных датах для семьи
С этим немного сложнее, так как предполагается хранить и использовать для поздравления такие даты как дни свадеб, годовщины, памятные даты.
Опять-таки БД для этого прекрасно подойдёт, хоть и дат будет не так много.

=== Поздравление с различными праздниками
В идеале чтобы это была интеграция с каким-нибудь API праздников или список государственных праздников, чтобы можно было увеличить количество поводов для радости.
При этом, необходимо учесть таки даты как День Радио, день Строителя и прочее, нужно будет принять решение, будут они в этом пункте или во втором.

=== Интеграция с сервисом погоды
Банальная приколюха, не понятно насколько она будет полезна, но можно к примеру вставлять кратко прогноз погоды в поздравления или напоминания.

=== Интеграция с chatGPT
В перспективе хотелось бы чтобы была возможность призвать прям в чате Telegram ChatGPT и задать ему любой вопрос. Ранее уже был опыт интеграции с API OpenAI.